/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing AssignTargetImageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssignTargetImageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssignTargetImageResponse
        //private AssignTargetImageResponse instance;

        public AssignTargetImageResponseTests()
        {
            // TODO uncomment below to create an instance of AssignTargetImageResponse
            //instance = new AssignTargetImageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssignTargetImageResponse
        /// </summary>
        [Fact]
        public void AssignTargetImageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssignTargetImageResponse
            //Assert.IsType<AssignTargetImageResponse>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'ImageId'
        /// </summary>
        [Fact]
        public void ImageIdTest()
        {
            // TODO unit test for the property 'ImageId'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }

    }

}
