/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.13 interdependent-karson
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing BroadcastMessageRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BroadcastMessageRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BroadcastMessageRequest
        //private BroadcastMessageRequest instance;

        public BroadcastMessageRequestTests()
        {
            // TODO uncomment below to create an instance of BroadcastMessageRequest
            //instance = new BroadcastMessageRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BroadcastMessageRequest
        /// </summary>
        [Fact]
        public void BroadcastMessageRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BroadcastMessageRequest
            //Assert.IsType<BroadcastMessageRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Transport'
        /// </summary>
        [Fact]
        public void TransportTest()
        {
            // TODO unit test for the property 'Transport'
        }
        /// <summary>
        /// Test the property 'CoapPath'
        /// </summary>
        [Fact]
        public void CoapPathTest()
        {
            // TODO unit test for the property 'CoapPath'
        }

    }

}
