/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.2.4 curable-andres
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing CertificateInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CertificateInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CertificateInfo
        //private CertificateInfo instance;

        public CertificateInfoTests()
        {
            // TODO uncomment below to create an instance of CertificateInfo
            //instance = new CertificateInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CertificateInfo
        /// </summary>
        [Fact]
        public void CertificateInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CertificateInfo
            //Assert.IsType<CertificateInfo>(instance);
        }


        /// <summary>
        /// Test the property 'CertificateSerial'
        /// </summary>
        [Fact]
        public void CertificateSerialTest()
        {
            // TODO unit test for the property 'CertificateSerial'
        }
        /// <summary>
        /// Test the property 'Expires'
        /// </summary>
        [Fact]
        public void ExpiresTest()
        {
            // TODO unit test for the property 'Expires'
        }

    }

}
