/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.6.1 squirming-codi
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing CollectionStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollectionStats
        //private CollectionStats instance;

        public CollectionStatsTests()
        {
            // TODO uncomment below to create an instance of CollectionStats
            //instance = new CollectionStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollectionStats
        /// </summary>
        [Fact]
        public void CollectionStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollectionStats
            //Assert.IsType<CollectionStats>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceCount'
        /// </summary>
        [Fact]
        public void DeviceCountTest()
        {
            // TODO unit test for the property 'DeviceCount'
        }
        /// <summary>
        /// Test the property 'OutputCount'
        /// </summary>
        [Fact]
        public void OutputCountTest()
        {
            // TODO unit test for the property 'OutputCount'
        }
        /// <summary>
        /// Test the property 'FirmwareCount'
        /// </summary>
        [Fact]
        public void FirmwareCountTest()
        {
            // TODO unit test for the property 'FirmwareCount'
        }
        /// <summary>
        /// Test the property 'BlobCount'
        /// </summary>
        [Fact]
        public void BlobCountTest()
        {
            // TODO unit test for the property 'BlobCount'
        }
        /// <summary>
        /// Test the property 'GatewayCount'
        /// </summary>
        [Fact]
        public void GatewayCountTest()
        {
            // TODO unit test for the property 'GatewayCount'
        }
        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Fact]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Fact]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }
        /// <summary>
        /// Test the property 'Blobs'
        /// </summary>
        [Fact]
        public void BlobsTest()
        {
            // TODO unit test for the property 'Blobs'
        }
        /// <summary>
        /// Test the property 'Gateways'
        /// </summary>
        [Fact]
        public void GatewaysTest()
        {
            // TODO unit test for the property 'Gateways'
        }

    }

}
