/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.2 subversive-jamila
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceStats
        //private DeviceStats instance;

        public DeviceStatsTests()
        {
            // TODO uncomment below to create an instance of DeviceStats
            //instance = new DeviceStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceStats
        /// </summary>
        [Fact]
        public void DeviceStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceStats
            //Assert.IsType<DeviceStats>(instance);
        }


        /// <summary>
        /// Test the property 'BytesUpstream'
        /// </summary>
        [Fact]
        public void BytesUpstreamTest()
        {
            // TODO unit test for the property 'BytesUpstream'
        }
        /// <summary>
        /// Test the property 'BytesDownstream'
        /// </summary>
        [Fact]
        public void BytesDownstreamTest()
        {
            // TODO unit test for the property 'BytesDownstream'
        }
        /// <summary>
        /// Test the property 'MessagesUpstream'
        /// </summary>
        [Fact]
        public void MessagesUpstreamTest()
        {
            // TODO unit test for the property 'MessagesUpstream'
        }
        /// <summary>
        /// Test the property 'MessagesDownstream'
        /// </summary>
        [Fact]
        public void MessagesDownstreamTest()
        {
            // TODO unit test for the property 'MessagesDownstream'
        }
        /// <summary>
        /// Test the property 'SessionCount'
        /// </summary>
        [Fact]
        public void SessionCountTest()
        {
            // TODO unit test for the property 'SessionCount'
        }

    }

}
