/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.1 busy-janay
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing Device
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Device
        //private Device instance;

        public DeviceTests()
        {
            // TODO uncomment below to create an instance of Device
            //instance = new Device();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Device
        /// </summary>
        [Fact]
        public void DeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Device
            //Assert.IsType<Device>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Fact]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Imsi'
        /// </summary>
        [Fact]
        public void ImsiTest()
        {
            // TODO unit test for the property 'Imsi'
        }
        /// <summary>
        /// Test the property 'Imei'
        /// </summary>
        [Fact]
        public void ImeiTest()
        {
            // TODO unit test for the property 'Imei'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

    }

}
