/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.8 adopted-kali
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing Firmware
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmwareTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Firmware
        //private Firmware instance;

        public FirmwareTests()
        {
            // TODO uncomment below to create an instance of Firmware
            //instance = new Firmware();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Firmware
        /// </summary>
        [Fact]
        public void FirmwareInstanceTest()
        {
            // TODO uncomment below to test "IsType" Firmware
            //Assert.IsType<Firmware>(instance);
        }


        /// <summary>
        /// Test the property 'ImageId'
        /// </summary>
        [Fact]
        public void ImageIdTest()
        {
            // TODO unit test for the property 'ImageId'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Fact]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Sha256'
        /// </summary>
        [Fact]
        public void Sha256Test()
        {
            // TODO unit test for the property 'Sha256'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
