/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.7.0 actionable-aryanna
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing FirmwareStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmwareStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FirmwareStats
        //private FirmwareStats instance;

        public FirmwareStatsTests()
        {
            // TODO uncomment below to create an instance of FirmwareStats
            //instance = new FirmwareStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FirmwareStats
        /// </summary>
        [Fact]
        public void FirmwareStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" FirmwareStats
            //Assert.IsType<FirmwareStats>(instance);
        }


        /// <summary>
        /// Test the property 'FirmwareImageSize'
        /// </summary>
        [Fact]
        public void FirmwareImageSizeTest()
        {
            // TODO unit test for the property 'FirmwareImageSize'
        }

    }

}
