/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.4.0 lean-joline
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayDeviceConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayDeviceConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayDeviceConfig
        //private GatewayDeviceConfig instance;

        public GatewayDeviceConfigTests()
        {
            // TODO uncomment below to create an instance of GatewayDeviceConfig
            //instance = new GatewayDeviceConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayDeviceConfig
        /// </summary>
        [Fact]
        public void GatewayDeviceConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayDeviceConfig
            //Assert.IsType<GatewayDeviceConfig>(instance);
        }


        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
