/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayCertificateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayCertificateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayCertificateResponse
        //private GatewayCertificateResponse instance;

        public GatewayCertificateResponseTests()
        {
            // TODO uncomment below to create an instance of GatewayCertificateResponse
            //instance = new GatewayCertificateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayCertificateResponse
        /// </summary>
        [Fact]
        public void GatewayCertificateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayCertificateResponse
            //Assert.IsType<GatewayCertificateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Certificates'
        /// </summary>
        [Fact]
        public void CertificatesTest()
        {
            // TODO unit test for the property 'Certificates'
        }

    }

}
