/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.9.6 authoritarian-betty
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing GatewayConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GatewayConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GatewayConfig
        //private GatewayConfig instance;

        public GatewayConfigTests()
        {
            // TODO uncomment below to create an instance of GatewayConfig
            //instance = new GatewayConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GatewayConfig
        /// </summary>
        [Fact]
        public void GatewayConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" GatewayConfig
            //Assert.IsType<GatewayConfig>(instance);
        }


        /// <summary>
        /// Test the property 'Ciot'
        /// </summary>
        [Fact]
        public void CiotTest()
        {
            // TODO unit test for the property 'Ciot'
        }
        /// <summary>
        /// Test the property 'Inet'
        /// </summary>
        [Fact]
        public void InetTest()
        {
            // TODO unit test for the property 'Inet'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
