/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing ImageUploadReference
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageUploadReferenceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImageUploadReference
        //private ImageUploadReference instance;

        public ImageUploadReferenceTests()
        {
            // TODO uncomment below to create an instance of ImageUploadReference
            //instance = new ImageUploadReference();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageUploadReference
        /// </summary>
        [Fact]
        public void ImageUploadReferenceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImageUploadReference
            //Assert.IsType<ImageUploadReference>(instance);
        }


        /// <summary>
        /// Test the property 'ImageRef'
        /// </summary>
        [Fact]
        public void ImageRefTest()
        {
            // TODO unit test for the property 'ImageRef'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Fact]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Fact]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }
        /// <summary>
        /// Test the property 'Sha256'
        /// </summary>
        [Fact]
        public void Sha256Test()
        {
            // TODO unit test for the property 'Sha256'
        }

    }

}
