/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.9.5 spattered-kelvin
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing InetMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InetMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InetMetadata
        //private InetMetadata instance;

        public InetMetadataTests()
        {
            // TODO uncomment below to create an instance of InetMetadata
            //instance = new InetMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InetMetadata
        /// </summary>
        [Fact]
        public void InetMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" InetMetadata
            //Assert.IsType<InetMetadata>(instance);
        }


        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }
        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Fact]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'RemoteAddress'
        /// </summary>
        [Fact]
        public void RemoteAddressTest()
        {
            // TODO unit test for the property 'RemoteAddress'
        }
        /// <summary>
        /// Test the property 'CertificateSerial'
        /// </summary>
        [Fact]
        public void CertificateSerialTest()
        {
            // TODO unit test for the property 'CertificateSerial'
        }

    }

}
