/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing ListImageStatesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListImageStatesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListImageStatesResponse
        //private ListImageStatesResponse instance;

        public ListImageStatesResponseTests()
        {
            // TODO uncomment below to create an instance of ListImageStatesResponse
            //instance = new ListImageStatesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListImageStatesResponse
        /// </summary>
        [Fact]
        public void ListImageStatesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListImageStatesResponse
            //Assert.IsType<ListImageStatesResponse>(instance);
        }


        /// <summary>
        /// Test the property 'States'
        /// </summary>
        [Fact]
        public void StatesTest()
        {
            // TODO unit test for the property 'States'
        }

    }

}
