/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.4 pettish-alleen
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing ListLabeledFirmwareResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListLabeledFirmwareResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListLabeledFirmwareResponse
        //private ListLabeledFirmwareResponse instance;

        public ListLabeledFirmwareResponseTests()
        {
            // TODO uncomment below to create an instance of ListLabeledFirmwareResponse
            //instance = new ListLabeledFirmwareResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListLabeledFirmwareResponse
        /// </summary>
        [Fact]
        public void ListLabeledFirmwareResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListLabeledFirmwareResponse
            //Assert.IsType<ListLabeledFirmwareResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Fact]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }

    }

}
