/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.16 spooky-devante
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing NetworkOperator
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkOperatorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkOperator
        //private NetworkOperator instance;

        public NetworkOperatorTests()
        {
            // TODO uncomment below to create an instance of NetworkOperator
            //instance = new NetworkOperator();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkOperator
        /// </summary>
        [Fact]
        public void NetworkOperatorInstanceTest()
        {
            // TODO uncomment below to test "IsType" NetworkOperator
            //Assert.IsType<NetworkOperator>(instance);
        }


        /// <summary>
        /// Test the property 'Mcc'
        /// </summary>
        [Fact]
        public void MccTest()
        {
            // TODO unit test for the property 'Mcc'
        }
        /// <summary>
        /// Test the property 'Mnc'
        /// </summary>
        [Fact]
        public void MncTest()
        {
            // TODO unit test for the property 'Mnc'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

    }

}
