/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.1.15 disproved-darryl
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing OutputLogResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OutputLogResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OutputLogResponse
        //private OutputLogResponse instance;

        public OutputLogResponseTests()
        {
            // TODO uncomment below to create an instance of OutputLogResponse
            //instance = new OutputLogResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OutputLogResponse
        /// </summary>
        [Fact]
        public void OutputLogResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OutputLogResponse
            //Assert.IsType<OutputLogResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

    }

}
