/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.3 pitch-dark-elza
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing SignCertificateBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignCertificateBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignCertificateBody
        //private SignCertificateBody instance;

        public SignCertificateBodyTests()
        {
            // TODO uncomment below to create an instance of SignCertificateBody
            //instance = new SignCertificateBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignCertificateBody
        /// </summary>
        [Fact]
        public void SignCertificateBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignCertificateBody
            //Assert.IsType<SignCertificateBody>(instance);
        }


        /// <summary>
        /// Test the property 'GatewayId'
        /// </summary>
        [Fact]
        public void GatewayIdTest()
        {
            // TODO unit test for the property 'GatewayId'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'Csr'
        /// </summary>
        [Fact]
        public void CsrTest()
        {
            // TODO unit test for the property 'Csr'
        }

    }

}
