/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 4.6.1 squirming-codi
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateDeviceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateDeviceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateDeviceRequest
        //private UpdateDeviceRequest instance;

        public UpdateDeviceRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateDeviceRequest
            //instance = new UpdateDeviceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateDeviceRequest
        /// </summary>
        [Fact]
        public void UpdateDeviceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateDeviceRequest
            //Assert.IsType<UpdateDeviceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Fact]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }
        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

    }

}
