/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.Lab5e.Span.Api;
using Com.Lab5e.Span.Model;
using Com.Lab5e.Span.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.Lab5e.Span.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCollectionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCollectionBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCollectionBody
        //private UpdateCollectionBody instance;

        public UpdateCollectionBodyTests()
        {
            // TODO uncomment below to create an instance of UpdateCollectionBody
            //instance = new UpdateCollectionBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCollectionBody
        /// </summary>
        [Fact]
        public void UpdateCollectionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCollectionBody
            //Assert.IsType<UpdateCollectionBody>(instance);
        }


        /// <summary>
        /// Test the property 'TeamId'
        /// </summary>
        [Fact]
        public void TeamIdTest()
        {
            // TODO unit test for the property 'TeamId'
        }
        /// <summary>
        /// Test the property 'Firmware'
        /// </summary>
        [Fact]
        public void FirmwareTest()
        {
            // TODO unit test for the property 'Firmware'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
