/*
 * The Span API
 *
 * API for device, collection, output and firmware management
 *
 * The version of the OpenAPI document: 5.0.5 contented-jamila
 * Contact: dev@lab5e.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.Lab5e.Span.Client.OpenAPIDateConverter;

namespace Com.Lab5e.Span.Model
{
    /// <summary>
    /// The image version log contains all reported versions and firmware images  by a device. The entries in the version log is independent of the image list;  if an image is removed the entry will remain in the version log.
    /// </summary>
    [DataContract(Name = "ImageVersionEntry")]
    public partial class ImageVersionEntry : IEquatable<ImageVersionEntry>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImageVersionEntry" /> class.
        /// </summary>
        /// <param name="deviceId">deviceId.</param>
        /// <param name="imageId">imageId.</param>
        /// <param name="imageVersion">imageVersion.</param>
        /// <param name="imageLabel">imageLabel.</param>
        /// <param name="reported">reported.</param>
        public ImageVersionEntry(string deviceId = default(string), string imageId = default(string), string imageVersion = default(string), string imageLabel = default(string), string reported = default(string))
        {
            this.DeviceId = deviceId;
            this.ImageId = imageId;
            this.ImageVersion = imageVersion;
            this.ImageLabel = imageLabel;
            this.Reported = reported;
        }

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [DataMember(Name = "deviceId", EmitDefaultValue = false)]
        public string DeviceId { get; set; }

        /// <summary>
        /// Gets or Sets ImageId
        /// </summary>
        [DataMember(Name = "imageId", EmitDefaultValue = false)]
        public string ImageId { get; set; }

        /// <summary>
        /// Gets or Sets ImageVersion
        /// </summary>
        [DataMember(Name = "imageVersion", EmitDefaultValue = false)]
        public string ImageVersion { get; set; }

        /// <summary>
        /// Gets or Sets ImageLabel
        /// </summary>
        [DataMember(Name = "imageLabel", EmitDefaultValue = false)]
        public string ImageLabel { get; set; }

        /// <summary>
        /// Gets or Sets Reported
        /// </summary>
        [DataMember(Name = "reported", EmitDefaultValue = false)]
        public string Reported { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImageVersionEntry {\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  ImageId: ").Append(ImageId).Append("\n");
            sb.Append("  ImageVersion: ").Append(ImageVersion).Append("\n");
            sb.Append("  ImageLabel: ").Append(ImageLabel).Append("\n");
            sb.Append("  Reported: ").Append(Reported).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ImageVersionEntry);
        }

        /// <summary>
        /// Returns true if ImageVersionEntry instances are equal
        /// </summary>
        /// <param name="input">Instance of ImageVersionEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ImageVersionEntry input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DeviceId == input.DeviceId ||
                    (this.DeviceId != null &&
                    this.DeviceId.Equals(input.DeviceId))
                ) && 
                (
                    this.ImageId == input.ImageId ||
                    (this.ImageId != null &&
                    this.ImageId.Equals(input.ImageId))
                ) && 
                (
                    this.ImageVersion == input.ImageVersion ||
                    (this.ImageVersion != null &&
                    this.ImageVersion.Equals(input.ImageVersion))
                ) && 
                (
                    this.ImageLabel == input.ImageLabel ||
                    (this.ImageLabel != null &&
                    this.ImageLabel.Equals(input.ImageLabel))
                ) && 
                (
                    this.Reported == input.Reported ||
                    (this.Reported != null &&
                    this.Reported.Equals(input.Reported))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DeviceId != null)
                {
                    hashCode = (hashCode * 59) + this.DeviceId.GetHashCode();
                }
                if (this.ImageId != null)
                {
                    hashCode = (hashCode * 59) + this.ImageId.GetHashCode();
                }
                if (this.ImageVersion != null)
                {
                    hashCode = (hashCode * 59) + this.ImageVersion.GetHashCode();
                }
                if (this.ImageLabel != null)
                {
                    hashCode = (hashCode * 59) + this.ImageLabel.GetHashCode();
                }
                if (this.Reported != null)
                {
                    hashCode = (hashCode * 59) + this.Reported.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
